{% set version = "1.1.0" %}

package:
  name: pectus
  version: {{ version }}

source:
  url: https://github.com/l0keshG/pectus_exercise

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
